### ISSUE TITLE
Use DiffPlex.UWP for displaying commit diff

### ISSUE THREAD

**Issue by BobbyESP** [fluenthub-community/FluentHub#10]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

We can get the text comparer from [this](https://github.com/veler/DevToys) repo.

### Relevant Assets

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/60316747/150683723-f8364213-26af-4fd9-ad0e-dba1e7fc0c02.png">

**Comment by onein528** [comment]
VERY GOOD.
LOOKS GOOD TO ME!!!!!!!!

I thought that the UI of the source code or diff were the most troublesome points, but this is a very good idea.

**Comment by BobbyESP** [comment]
Nice!

**Comment by BobbyESP** [comment]
That app also has Markdown if u want to improve the system that already have this one.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/60316747/150685289-7529fe68-9820-4a82-89cb-1800ac429329.png">

**Comment by onein528** [comment]
Yeah, Get the same experience as a browser with WebView, or simplify your code with existing markdown tools.
Either way, fixing the relative path is mandatory.

**Comment by onein528** [comment]
Another reason I'm afraid to use markdown controls is that I can't change the style. With WebView, we can get the same experience as a GitHub site by simply inserting the rendered Html code into the default Html file(included css file with `<style>`), but we can't change the style of the markdown controls.

**Comment by BobbyESP** [comment]
Ahh ok. So ut's better using the WebView one, no?

**Comment by onein528** [comment]
It's maybe better than markdown controls

**Comment by onein528** [comment]
> We can get the text comparer from [this](https://github.com/veler/DevToys) repo.
> 
> <img alt="image" width="1660" src="https://user-images.githubusercontent.com/60316747/150683723-f8364213-26af-4fd9-ad0e-dba1e7fc0c02.png">

This use Monaco Editor for UWP
Looks like vscode code editor 💯

**Comment by BobbyESP** [comment]
> It's maybe better than markdown controls

Ok, nice

**Comment by BobbyESP** [comment]
> > We can get the text comparer from [this](https://github.com/veler/DevToys) repo.
> > 
> > <img alt="image" width="1660" src="https://user-images.githubusercontent.com/60316747/150683723-f8364213-26af-4fd9-ad0e-dba1e7fc0c02.png">
> 
> This use Monaco Editor for UWP
> Looks like vscode code editor 💯 

Ok, nice, so we can use this one with syntax highlightning

**Comment by onein528** [comment]
Ohh, sorry. that comment was misleading.

- **markdown**
Markdown controls can't specify GitHub stylesheets, so GitHub original font sizes, colors, and syntax highlighting don't apply.
- **Code editor**
The code editor is perfectly fine with this editor. I wanted to tell you that it's called the Monaco Editor and is also used in the editor part of VS Code.

Sorry :F

**Comment by BobbyESP** [comment]
Ohhh, ok! Thakns for the info. And dont worry :)

**Comment by onein528** [comment]
> That app also has Markdown if u want to improve the system that already have this one.
> 
> 
> 
> <img width="1920" alt="image" src="https://user-images.githubusercontent.com/60316747/150685289-7529fe68-9820-4a82-89cb-1800ac429329.png">
> 
> 

this use WebView with github style sheets.

We maybe use Markdown block control of toolkit, if we can customize styles.

**Comment by onein528** [comment]
> We can get the text comparer from [this](https://github.com/veler/DevToys) repo.
> 
> 
> 
> <img width="1660" alt="image" src="https://user-images.githubusercontent.com/60316747/150683723-f8364213-26af-4fd9-ad0e-dba1e7fc0c02.png">
> 
> 

I will use textblock styling with monospace for the time being.

currently, i dont know how to use it which based on Web.

**Comment by onein528** [comment]
maybe use more lightweight library :0

**Comment by jonasnordlund** [comment]
I've looked so hard for a free/open source UWP or WinUI syntax highlighting control. So far only found something in alpha, a paid control, and this. It's unfortunate because yes, this is basically an IDE class control. One unorthodox option is to use WebView2 (which ought to feel lighter) together with something like [Codemirror](https://codemirror.net/). It has several features including a [merge addon](https://codemirror.net/demo/merge.html) based on https://github.com/google/diff-match-patch for diff style formatting.

**Comment by onein528** [comment]
Thank you your commenting. I planned to use [MonacoEditor.UWP](https://github.com/hawkerm/monaco-editor-uwp) but it is very heavy and web-base. so I maybe will use [DiffPlex.UWP](https://github.com/mmanela/diffplex) for more flexible and customizable which has used in [Notepads](https://github.com/JasonStein/Notepads, [TextDiff-UWP](https://github.com/luandersonn/TextDiff-UWP)). I will also take a look yours!
