### ISSUE TITLE
Add keyboard shortcut support

### ISSUE THREAD

**Issue by luandersonn** [fluenthub-community/FluentHub#100]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### Description

Adding support for keyboard and mouse shortcuts would increase productivity with FluentHub.

Common shortcuts:

Shortcut | Description
:-|:-
`Ctrl` + `T` | Opens a new tab
`Ctrl` + `W` | Closes the current tab
`Ctrl` + `Tab` | Go to the next tab
`Ctrl` + `Shift` + `Tab` | Go to the previous tab
`Alt` + `Left`, `Back` (mouse) | Navigate back
`Alt` + `Right`, `Forward` (mouse) | Navigate forward
`F5` | Refresh the page

And more

**Comment by onein528** [comment]
maybe we can use like:

```xaml
<KeyboardAccelerator Key="T" Modifiers="Control">
    <i:Interaction.Behaviors>
        <icore:EventTriggerBehavior EventName="Invoked">
            <icore:InvokeCommandAction Command="{x:Bind ViewModel.AddNewInstanceAcceleratorCommand}" />
        </icore:EventTriggerBehavior>
    </i:Interaction.Behaviors>
</KeyboardAccelerator>
```
And seems like all click events need to go to the ViewModel.

**Comment by luandersonn** [comment]
Not implemented yet

**Comment by onein528** [comment]
oh sorry..
