### ISSUE TITLE
Add new logos for stable version

### ISSUE THREAD

**Issue by onein528** [fluenthub-community/FluentHub#101]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

**Comment by esibruti** [comment]
@onein528 It was done in a hurry but it's an idea I had, what do you think?
![image](https://user-images.githubusercontent.com/78214358/161049084-8e1ec152-8e15-46cf-bda3-dd829e2f5d26.png)

**Comment by onein528** [comment]
woow, nice idea! I have now asked one of my friends to create a concept for a logo. But thank you for the concept. Perhaps we may be able to use this.

FYI, The white square frame around the logo was created with the Mac application in mind, but we would like to remove it for the new logo.
I also have great respect for Files and would like to use an app logo with fluent tones like the Files logo.

![i](https://raw.githubusercontent.com/files-community/Files/main/src/Files.Uwp/Assets/AppTiles/StoreLogo.scale-400.png)

![i](https://raw.githubusercontent.com/files-community/Files/main/src/Files.Uwp/Assets/AppTilesDev/StoreLogo.scale-400.png)

**Comment by esibruti** [comment]
Ahh, I get it. Yes, for a Fluent application it is good to have a fluent icon.

**Comment by esibruti** [comment]
I can try

**Comment by onein528** [comment]
very thank you😀

**Comment by esibruti** [comment]
@onein528 Do you have a color palette you want to use?

**Comment by onein528** [comment]
just github-like colors!

**Comment by esibruti** [comment]
![teste](https://user-images.githubusercontent.com/78214358/161067126-2f332937-f950-4100-8e98-2fb961b5912d.png)
Draft 1, opinion @onein528

**Comment by onein528** [comment]
yes! i know. can you change color palett between dev and stable?

and 
![image](https://user-images.githubusercontent.com/62196528/161067824-8a5ebded-f85b-41a9-becc-80d5490063a5.png)

maybe dont need circle but i know this is draft.

**Comment by onein528** [comment]
can you code our discord? https://discord.gg/4Zy6H7cU

**Comment by onein528** [comment]
> @onein528 It was done in a hurry but it's an idea I had, what do you think? ![image](https://user-images.githubusercontent.com/78214358/161049084-8e1ec152-8e15-46cf-bda3-dd829e2f5d26.png)

@esibruti Can you give me this SVG file, with the DEV labels removed and colorized to look like the current logo as soon as you can? (I have no much time since I am student and have many exams)

![image](https://user-images.githubusercontent.com/62196528/166867196-f02a18f3-eac0-4a30-89fc-0a6173b7aff2.png)

I have colorized with two graduation point(1: #ED4E50, 2: #F06F00)

![image](https://user-images.githubusercontent.com/62196528/166867339-e751555f-87e5-4278-923f-d9a6690d5a70.png)

taken from discussion page like:

![image](https://user-images.githubusercontent.com/62196528/166867365-d27868eb-4e67-451b-927e-3e88dddc5117.png)

If you have much time, I want you to prepare more color variation.

1: #2568F6, 2: #804CDA
1: #DB459F, 2: #2568F6
1: #9866F0, 2: #EB4D50

**Comment by onein528** [comment]
I apologize for any inconvenience this has caused you in the past.

**Comment by onein528** [comment]
@esibruti some progress?

**Comment by esibruti** [comment]
@onein528 I really don't have any time these days but here is the file:
![gitLogo](https://user-images.githubusercontent.com/78214358/168242101-dbf338bd-e1ba-4021-9fad-b9211020882b.svg)

**Comment by onein528** [comment]
wow nice!

**Comment by onein528** [comment]
![fluenthub-new-logo](https://user-images.githubusercontent.com/62196528/168246657-09cfd323-17e5-474a-8373-91e76724746a.svg)

how do you feel?
