### ISSUE TITLE
FluentHub Crashes after authentication 

### ISSUE THREAD

**Issue by AstroX809** [fluenthub-community/FluentHub#104]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Beta

### What FluentHub version/architecture are you seeing the problem on?

0.8.25.0

### Description

I opened the app, I clicked on "Start Setup", the app asked me to login with me Github account, after authenticating the app immediately crashed.

### Steps To Reproduce

1. Open the app
2. Click "Start Setup"
3. Click "Open with your browser"
4. Authenticate in the Github page
5. The app crashes

### Expected behavior

I expected the app to take me to the next page in the setup process.

### Relevant Assets

https://streamable.com/ngcdv5

**Comment by onein528** [comment]
Very important. can you build this app with this [docs](https://github.com/fluenthub-community/FluentHub/blob/main/docs/building-from-source.md)?
If not possible, I'm sorry, but can you wait until I commit the PR to log the authentication phase? I will work on this as a top priority.

**Comment by senolfndk** [comment]
ayen is crashing on me too

**Comment by onein528** [comment]
I was able to confirm this issue. It appears to have contained a critical bug. The package has been removed. The only way to run this application is to build. sorry.

Pls buid from here https://github.com/fluenthub-community/FluentHub/blob/main/docs/building-from-source.md

**Comment by senolfndk** [comment]
crashing

https://user-images.githubusercontent.com/52818836/161305548-c4f1706f-8e0f-4cb1-88c9-1393bd829c3f.mp4

**Comment by onein528** [comment]
okey which version? 0.7.13?

**Comment by senolfndk** [comment]
0.7.13 version

**Comment by onein528** [comment]
confirmed. I will fix sorry.

**Comment by senolfndk** [comment]
ok

**Comment by onein528** [comment]
@senolfndk this is first launch? yet dont auth?

**Comment by onein528** [comment]
Building with the same build version DEBUG configuration will absolutely succeed. However, when run with a RELEASE build, it seems to fail after authentication. My thinking is that in the RELEASE build, the exception that should be caught by try-catch is not being caught.

**Comment by johngagefaulkner** [comment]
> Building with the same build version DEBUG configuration will absolutely succeed. However, when run with a RELEASE build, it seems to fail after authentication. My thinking is that in the RELEASE build, the exception that should be caught by try-catch is not being caught.

Building `0.7.13` with DEBUG configuration does not succeed, either. The application does not "crash" but it sits at the "loading" screen after authentication forever (never continues/progresses forward.)

**Comment by onein528** [comment]
@johngagefaulkner Sorry for the inconveniences. your feedback is very important. thank you. I launched v0.7.13 right now and it seems to stop when OnLaunch or OnActivated takes too long. After that version the post-authentication behavior has changed.

Can you build the latest head/main branch? If you can, I will tag v0.7.15

**Comment by johngagefaulkner** [comment]
> @johngagefaulkner Sorry for the inconveniences. your feedback is very important. thank you. I launched v0.7.13 right now and it seems to stop when OnLaunch or OnActivated takes too long. After that version the post-authentication behavior has changed.
> 
> 
> 
> Please these steps:
> 
> 
> 
> 1. Uninstall app
> 
> 2. Re-generate client secret and put them to config file.
> 
> 3. Build latest head/main branch.
> 
> 4. Let me know if app success.
> 
> 
> 
> If so, I will tag v0.7.15

Yeah, give me 30 minutes, I went to get breakfast. Then I'll build & test.

**Comment by onein528** [comment]
I did. from [sideload pipeline artifacts](https://dev.azure.com/fluenthub-community/FluentHub/_build/results?buildId=520&view=artifacts&pathAsName=false&type=publishedArtifacts)

![image](https://user-images.githubusercontent.com/62196528/161766493-376607b9-5872-4d00-928a-c934d3954adb.png)

Same issue.

**Comment by johngagefaulkner** [comment]
@onein528 Are you saying you just tested the most recent build and it isn't working for you, either? Is it throwing an exception? If so, what's the error message?

**Comment by onein528** [comment]
latest version configured RELEASE does not work(same. suspending). but latest version configured DEBUG does work property.

**Comment by onein528** [comment]
It is impossible to know what is wrong with an application in the RELEASE configuration because it cannot be debugged. However, when I run the app in DEBUG configuration, it succeeds for some reason.

**Comment by senolfndk** [comment]
https://user-images.githubusercontent.com/52818836/161771061-39da2fcc-c6ba-4b27-8df4-6d0d49a1ebad.mp4

🙁

**Comment by onein528** [comment]
can you build latest branch?

**Comment by senolfndk** [comment]
![Ekran görüntüsü 2022-04-05 170648](https://user-images.githubusercontent.com/52818836/161772456-74f6adad-cb7b-4d5d-af25-07feb73f52fa.png)

**Comment by onein528** [comment]
appinstaller cannot be launch.

use msixbundle

**Comment by onein528** [comment]
yes

**Comment by senolfndk** [comment]
> Evet

i already installed this

**Comment by onein528** [comment]
can you build source code of latest head/main branch?

**Comment by senolfndk** [comment]
> en son ana/ana dalın kaynak kodunu oluşturabilir misiniz?

I don't know how to generate code

**Comment by onein528** [comment]
OK. now, the app package, configured RELEASE, will be remove until become stable version V1.

We do apologize for any inconvenience caused. but i cannot found what is wrong with sideload package. so if you want to use this, you need to build app. if you cannot, please wait when published on Microsoft Store(v1.0.0).

**Comment by BobbyESP** [comment]
This still occuring or the issue can be closed?

**Comment by nathayoung** [comment]
So far when I build, I keep getting it.  I'm building every day after any changes. The app knows it's me but the UI doesn't.  I'm assuming that has something to do with stored credentials. I can send screenshots and logs later, but I have to get ready for work.

**Comment by onein528** [comment]
Thanks. I wonder we can build successfully absolutely. so we are looking forward failed logs.

**Comment by nathayoung** [comment]
Sure thing.  I'll get back on this later today after work.

**Comment by BobbyESP** [comment]
Okey please send the logs when you are able to. No problem!

**Comment by nathayoung** [comment]
I'm not 100% sure what you need/want but I tried to gather what I think may be helpful.  Let me know if you need anything else. 

Just so you know, I'm running Win 11 Dev Build 22598, using Visual Studio 2022 v17.1.5, and running off the Main branch which appears to be FluentHub v0.7.13.0.

Here's the build section:

https://user-images.githubusercontent.com/46688736/164554189-faa8a458-a42f-45a3-ad2e-5e458f87bf2e.mp4

And the deploy.  I tried to show what I was attempting to describe earlier with the app knowing it's me but the UI not (that explanation is starting to not make any sense to me 😂).  Basically, you can see that the Home page doesn't recognize my account, but when I go to Notifications, it's pulling those in perfectly.  

https://user-images.githubusercontent.com/46688736/164554566-1d5e2248-bb6d-4c28-b733-5685b93e20c7.mp4

And here's the sign in issue still occuring: 

https://user-images.githubusercontent.com/46688736/164554718-e44420b1-9472-43d7-90eb-74750dfd2625.mp4


Here's the log.  I don't see this capturing the sign in, just the failure to get the user information on the Home page.
[Log20220421.log](https://github.com/fluenthub-community/FluentHub/files/8535166/Log20220421.log)

**Comment by BobbyESP** [comment]
Yeah, we haven't implemented yet all the things to the log maker. I'm gonna try to reproduce the problem and i tell you.

**Comment by BobbyESP** [comment]
For me all worked well. Now i can't continue investigating because i need to go to sleep. Tomorrow i'll take a deep investigation, and if i cant found the problem, i dont know if you liked to make a screen sharing on Discord. Thanks for the report and sorry for the inconveniences.

**Comment by nathayoung** [comment]
Bummer.  This happens to me at work all the time, everything works for me but is broken for everyone else ha.  Thanks for taking a look.  As for the discord, the link in the README, at least for me, is just a link to the channel, not an invite.  When I click it I just get taken to the discord app, not the server/channel...

**Comment by BobbyESP** [comment]
Ohh, no problem, i change it now!

**Comment by BobbyESP** [comment]
https://discord.gg/geWQjmvTZV

**Comment by nathayoung** [comment]
Thanks!

**Comment by onein528** [comment]
I will make logging better in current PR. you can access log location in settings -> about page.
And please give your log file.

**Comment by BobbyESP** [comment]
He already sent the log -> https://github.com/fluenthub-community/FluentHub/files/8535166/Log20220421.log

**Comment by onein528** [comment]
I think code does not store signed in username to app settings manager.

**Comment by onein528** [comment]
@nathayoung nice feedback! thank you.

**Comment by BobbyESP** [comment]
#123 Take a look to this issue. If your problem is not solved, we will reopen the issue.

**Comment by onein528** [comment]
duplicate of #123
