### ISSUE TITLE
Navigate incorrect frame

### ISSUE THREAD

**Issue by onein528** [fluenthub-community/FluentHub#110]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

v0.7.13 (deving)

### Description

When returning to the previous frame, it does not go to the previous sub-frame page.

### Steps To Reproduce

1. click an issue/pr button
or
1. go to code view

### Expected behavior

navigate correct sub frame

### Relevant Assets

![image](https://user-images.githubusercontent.com/62196528/161077770-5d18079c-d095-4337-99d3-261e1804ac53.png)

![image](https://user-images.githubusercontent.com/62196528/161078279-756a503c-627f-4d0d-8152-92d8ca77b210.png)

**Comment by BobbyESP** [comment]
Maybe it's a good idea, but i dont know how the RAM usage will be impacted
