### ISSUE TITLE
Please submit builds in the releases tab

### ISSUE THREAD

**Issue by Advik-B** [fluenthub-community/FluentHub#116]
### Before you start...

- [X] Have you checked if similar issue have already been reported?
- [ ] Have you updated the FluentHub? You might be using an old version.

### Description

​

### Alternative solutions

​

### Relevant Assets

​

**Comment by BobbyESP** [comment]
We're taking a look to it because we are having some issues. We'll provide the bundle as fast as possible in next releases. By the moment, the only way to open/install the app is by compiling it by yourself. Sorry for the inconveniences.

**Comment by onein528** [comment]
I'm making sideload pipeline for GitHub release

https://github.com/fluenthub-community/FluentHub/blob/sideload-azure-pipelines/builds/azure-pipelines-sideload.yml

**Comment by onein528** [comment]
Uploaded. can you install? @Advik-B
