### ISSUE TITLE
There is no overview should be hidden after data loads up

### ISSUE THREAD

**Issue by HenryWu01** [fluenthub-community/FluentHub#124]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

0.7.13.0 | X64 | DEBUG

### Description

Where I use FluentHub to load organization's repository, It loads up. However the text ``There is no overview`` does not disappear.
![image](https://user-images.githubusercontent.com/99880210/164865927-d9715eef-5fb7-4f45-a648-25b09442dd71.png)

### Steps To Reproduce

1.Go to organization page
2.Randomly pick one organization
3.Wait for the data to load up
4.There is no overview never disappear

### Expected behavior

There is no overview disappear

**Comment by onein528** [comment]
now tracking

When query organization repository info, it fails because of oauth restriction. this is default settings so we need to handle this failure. maybe it caused by this reason.

**Comment by HenryWu01** [comment]
Actually this is my organization, for some other organization it fails with error message you said above. I also found that it sometimes freeze and crash when loading my organization.

**Comment by onein528** [comment]
ok. I'm fixing that

**Comment by HenryWu01** [comment]
Thank you :) I like this software so much :D

**Comment by onein528** [comment]
Updated the view model to dependency injection and improved the UI to make it easier to understand what the organization is about.

![image](https://user-images.githubusercontent.com/62196528/164885454-8e535ea2-6c10-445f-933a-d1cecbf85360.png)

I own this org so never gonna happen OAuthRestriction exception.
but other orgs:(

**Comment by HenryWu01** [comment]
Other organization will have OAuthRestriction, but for the origanzation you own, FluentHub may freeze and I did not found any exception relate to it.

**Comment by onein528** [comment]
crash app with no exception?

**Comment by HenryWu01** [comment]
Not from code I think. It was a layout issue. The app freeze but did not crash.
![image](https://user-images.githubusercontent.com/99880210/164885980-94b5153f-e8c5-4c30-8017-64b0d0ba4186.png)

**Comment by onein528** [comment]
this is happen when occur xaml unhandled exception. very interesting.

**Comment by HenryWu01** [comment]
It's my private organization. I don't know if you can reproduce the issue.
Here is the link https://github.com/ReXu-Island

**Comment by onein528** [comment]
ok, same issue

![image](https://user-images.githubusercontent.com/62196528/164886346-9db3a796-cb94-487f-aaba-ad38d25530fc.png)

**Comment by HenryWu01** [comment]
Let me see if there is an option to disable oauth app restriction.

**Comment by onein528** [comment]
here you are https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/disabling-oauth-app-access-restrictions-for-your-organization

**Comment by onein528** [comment]
app does nice work

![image](https://user-images.githubusercontent.com/62196528/164886581-f6e297f8-7787-4e03-abce-2fbc0da9d354.png)

**Comment by HenryWu01** [comment]
That's weird. Does not work on side. I will look into this

**Comment by onein528** [comment]
very weird.

**Comment by HenryWu01** [comment]
It sometimes can load the data, sometimes failed. I just success once and now I face the exact same issue

**Comment by onein528** [comment]
So far, what version you use? main branch? if you do so, check out to issuepr-event branch and build please and check those issues

Disabled restriction exception in app.

![image](https://user-images.githubusercontent.com/62196528/164886888-547e7ecb-81d7-417c-9cdc-87e536a9a4e4.png)

**Comment by HenryWu01** [comment]
This does not happen for my organization not, or can I say this freeze happen less often. However when I click into Files Community, got in and back, switch between Overview and Repositories tab, freeze might happen as well.

**Comment by HenryWu01** [comment]
![image](https://user-images.githubusercontent.com/99880210/164887220-806a1c73-2529-4d6c-821a-5e01b0d5b527.png)
![image](https://user-images.githubusercontent.com/99880210/164887230-42b3013d-5708-4aed-b43f-83323b52be5e.png)

**Comment by onein528** [comment]
what.... page does work correctly. but occur xaml unhandled exception

**Comment by onein528** [comment]
can you track when this occur using breakpoint?

**Comment by onein528** [comment]
First, here:

![image](https://user-images.githubusercontent.com/62196528/164889129-5297ab0d-d952-436b-83d2-76f2a6de8c1c.png)

**Comment by HenryWu01** [comment]
This breakpoint was triggered, now I might reproduce after clicking repository tab

**Comment by onein528** [comment]
ok

**Comment by HenryWu01** [comment]
I have done that. The exception was after the break point actually. When I click repository tab

**Comment by onein528** [comment]
ok. can you tell me more specific? your feedback is very very helpful and thank you!

**Comment by HenryWu01** [comment]
Now it's not reproducible again...This almost drive my crazy, I will report it again when it occurs.

**Comment by onein528** [comment]
if the exception occur again, please tell me and I will reopen.
