### ISSUE TITLE
30+ Minutes and it still didn't open with my Browser

### ISSUE THREAD

**Issue by hedhehd** [fluenthub-community/FluentHub#129]
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Beta

### What FluentHub version/architecture are you seeing the problem on?

The latest version 0.7.13

### Description

Not sure how this happened and why. But apparently, it doesn't work.

### Steps To Reproduce

1. At setup, click on Start Setup
2. Click on Open with your Browser

### Expected behavior

That it opens a web page telling me to authenticate with GitHub.

**Comment by BobbyESP** [comment]
What's your default browser?

**Comment by hedhehd** [comment]
I know why...
https://github.com/fluenthub-community/FluentHub/blob/main/docs/build-from-source.md
I missed that
