### ISSUE TITLE
App have unhandled exception Cannot convert Null to Int32

### ISSUE THREAD

**Issue by hedhehd** [fluenthub-community/FluentHub#130]
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Beta

### What FluentHub version/architecture are you seeing the problem on?

0.7.13.0 | X64 | DEBUG

### Description

Just fetched and it fixed #123 but it created another issue that I can't go to another person's GitHub or to the home via URL. Basically, you can't change the URL to another person's GitHub or to the home.

### Steps To Reproduce

1. Type something on the URL and hit enter

### Expected behavior

What I expected to happen was that it changes to the URL you gave.

**Comment by hedhehd** [comment]
You can just block the user to use another domain just GitHub and any other related.

**Comment by hedhehd** [comment]
![image](https://user-images.githubusercontent.com/81228260/165335836-3de8505e-469d-4f75-b13d-5dd149ee94ff.png)

**Comment by onein528** [comment]
> I can't go to another person's GitHub

This is with clicking user block button?

**Comment by hedhehd** [comment]
No not even repositories

**Comment by onein528** [comment]
I don't implement going via URL

**Comment by onein528** [comment]
cannot click repositories and users?

**Comment by hedhehd** [comment]
I can

**Comment by onein528** [comment]
ok. can you send me log file?

**Comment by hedhehd** [comment]
![image](https://user-images.githubusercontent.com/81228260/165336786-79d52481-7e76-4ffe-93f1-10e37dbf1f85.png)
And also Pull requests doesn't allow you

**Comment by hedhehd** [comment]
> ok. can you send me log file?
[Log20220426.log](https://github.com/fluenthub-community/FluentHub/files/8564629/Log20220426.log)

**Comment by hedhehd** [comment]
![image](https://user-images.githubusercontent.com/81228260/165337157-4878c22a-fdf6-4ca3-80b4-01c337dfcb29.png)
![image](https://user-images.githubusercontent.com/81228260/165337205-032a59df-85ad-451a-9aa4-97655b0c4678.png)
My pfp is blank

**Comment by onein528** [comment]
Yep. does not implement. very complicated about getting via GitHub API.

**Comment by hedhehd** [comment]
I'm gonna check

**Comment by hedhehd** [comment]
Btw I noticed you can't create issue or comment but I guess it's gonna be added soon

**Comment by hedhehd** [comment]
And I would suggest having a home page like GitHub so you can navigate through stuff and search for user or basically everything, not just your user site.

**Comment by hedhehd** [comment]
But I guess that's all I found

**Comment by hedhehd** [comment]
Is it normal that you can't interact with issues on the home page side bar and discussions?

**Comment by onein528** [comment]
Yes. I will add a little more very soon.

**Comment by onein528** [comment]
We would like various people to test the current state of the application, but few users have done so. This is because of the complex steps involved at build time. A means exists to remove this procedure.

**Comment by onein528** [comment]
And I am a student of Japanese. I dont have much time to develop this app. but I am working on this and spending as much time as I can on this.

**Comment by onein528** [comment]
Can you check out to GU7 branch, build, and confirm that this issue you have been opened have been fixed?

**Comment by hedhehd** [comment]
![image](https://user-images.githubusercontent.com/81228260/166109682-87017ba1-375e-45b0-a12e-e28dbe63ab7f.png)

**Comment by hedhehd** [comment]
![image](https://user-images.githubusercontent.com/81228260/166109697-1cca1b94-8c69-4f7c-a489-3f3ff93aa2b7.png)

**Comment by hedhehd** [comment]
And when I tried to reinstall it, this happens every time when I authenicate. It's just stuck at that screen.
![image](https://user-images.githubusercontent.com/81228260/166109831-4e299d57-bbca-455a-a017-59321c8167ad.png)

**Comment by onein528** [comment]
I cannot figure out with those screenshot. Can you track that?

- [ ] NullRef: owner (unknown page)
- [ ] NotSupported: Select()
- [ ] Stuck in auth page

**Comment by hedhehd** [comment]
No

**Comment by onein528** [comment]
Why?
