### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by iiAhmedYT** [fluenthub-community/FluentHub#132]
Hello,

Seems like the person who made the README.md isn't very familiar with discord invites. since the link in the readme file isn't a link you can actually join the server with (unless you are in the server it will send you to there).
However, creating an invite link is really simple on discord. You can even make it not expire :)
Googling that will take about 10 seconds since there's a top result answer and i currently don't have a screenshot of how it's done.

 Thanks alot

**Comment by onein528** [comment]
I will do that. But you can create PR to contribute as your name.
