### ISSUE TITLE
Following count raises exception or does nothing

### ISSUE THREAD

**Issue by nathayoung** [fluenthub-community/FluentHub#143]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Dev

### What FluentHub version/architecture are you seeing the problem on?

0.3.0 | X64 | DEBUG

### Description

Selecting the number of those following raises an exception or does nothing.

### Steps To Reproduce

1. Open application
2. On profile overview, click the number of those following which does nothing: <img width="168" alt="image" src="https://user-images.githubusercontent.com/46688736/168374221-470f2623-e30a-4fce-a682-2774d09c34c2.png">
3. On profile overview, click the number of followers and then click number of those following which raises exception

### Expected behavior

Clicking on the other following returns expected results:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/46688736/168374354-1d6f626c-8562-4787-acb6-2e7cb0f5dcce.png">

### Relevant Assets

Up to date: 
![image](https://user-images.githubusercontent.com/46688736/168350462-2761394f-53ae-4364-a3ef-bade77a545da.png)

Error:
![image](https://user-images.githubusercontent.com/46688736/168350553-020ca046-1ee8-4a2b-8d87-fbeee77f841d.png)

Debug results:
![image](https://user-images.githubusercontent.com/46688736/168350677-57dc3e7f-1181-4727-9f3c-8ad1b247fc52.png)

**Comment by onein528** [comment]
now, I am in school. when back home, I will go on this.

**Comment by onein528** [comment]
I can see this problem on my machine.
I will fix this.

Thank you for your feedback!

**Comment by onein528** [comment]
Fixed in e17357b
