### ISSUE TITLE
When there is no internet connection, the app crashes

### ISSUE THREAD

**Issue by onein528** [fluenthub-community/FluentHub#45]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Dev

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

As the title

### Steps To Reproduce

1. Open app with no internel connection

**Comment by luandersonn** [comment]
I propose to save some user data in the cache to use when the app is launched. After the app starts, authenticate the user and handle any connection errors.

**Comment by onein528** [comment]
yes. I think so. but I dont want to create caching helpers. and since the cause of the crash is Octokit.NET, I would like to use try-catch to get thier exceptions, log it, stop loading the page, and let ContentDialog inform the user that the internet has been disconnected.

**Comment by onein528** [comment]
Fixed in #108. This exception is handled.
