### ISSUE TITLE
Use fluent style on css

### ISSUE THREAD

**Issue by onein528** [fluenthub-community/FluentHub#58]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Dev

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

Create a Fluent System stylesheet(css).

**Comment by BobbyESP** [comment]
Ok, i need to see the libraty, but this is gonna be hard. Fluent Svelte is like a framework and we need to take a look to how it works

**Comment by onein528** [comment]
yes. i ll take a look.

**Comment by onein528** [comment]
testing

# header1
## header2
### header3
#### header4
##### header5
###### header6

- bullet1
- bullet2

table header|table header
---|---
table content|table content
table content|table content

```
# H1
## H2
### H3
#### H4
##### H5
###### H6
```

*asterisks* or _underscores_.

**asterisks** or __underscores__.

**asterisks**.

~~Scratch this.~~

> Blockquote

`inline code`

---

- [ ] task1
- [ ] task2
  - [ ] task2.1
  - [ ] task2.2
