### ISSUE TITLE
App takes too long to start

### ISSUE THREAD

**Issue by BobbyESP** [fluenthub-community/FluentHub#67]
**Describe the bug**
Same as title
**To Reproduce**
1. Open the app and see how it slow is.

**Expected behavior**
Fast app loading

**Screenshots (optional)**
Nope

**Version**
 - Windows:
 - FluentHub:

**Additional context**
Making the principal view another one away from the profile wich needs to load all the information may fix this issue

**Comment by BobbyESP** [comment]
I realised that that is taking too long is the sign in. We need to optimize it or open the app without signing in, and have a notification in-app telling you that you are getting signed in

**Comment by onein528** [comment]
this app cannot use without signing in.
notification page and home page use signed in user profile.

**Comment by BobbyESP** [comment]
I know. What we can do it's optimize the logging or doing a Custom Splash
Screen telling that you are getting signed and later open the app. Like
charcter map uwp

**Comment by onein528** [comment]
ok i love that

**Comment by BobbyESP** [comment]
Ok, nice!

**Comment by BobbyESP** [comment]
I'll try to code a little these days. They're terrible because of school

**Comment by onein528** [comment]
ohok 
And I now am publishing v0.7.1!

![image](https://user-images.githubusercontent.com/62196528/155089520-c9a9b9f2-2e52-42ec-a9e0-91d7e72b3f69.png)

**Comment by BobbyESP** [comment]
OH yes babyyy !!

**Comment by BobbyESP** [comment]
I woll anounce this in multiple discord servers to get more people!

**Comment by BobbyESP** [comment]
And maybe i know some friends to make us a logo. But probably we need to pay to him

**Comment by onein528** [comment]
ohh. I wanna pay.... but I maybe cannot. so if you are needed to pay, you dont have to. really.

**Comment by onein528** [comment]
release draft is seen in https://github.com/fluenthub-uwp/FluentHub/releases

**Comment by BobbyESP** [comment]
Ok, nice!

**Comment by onein528** [comment]
All right. I thought about this.

[Adding a custom splash means extending the display of the splash screen (Microsoft Docs)](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-a-customized-splash-screen#:~:text=The%20phrase%20%22extended%20splash%20screen%22%20in%20this%20topic%20refers%20to%20a%20splash%20screen%20that%20stays%20on%20the%20screen%20for%20an%20extended%20period%20of%20time.%20It%20does%20not%20mean%20a%20subclass%20that%20derives%20from%20the%20SplashScreen%20class.).

So, adding a splash causes further delay.

**Comment by onein528** [comment]
However, the delay in startup time is due to await in OnLaunch. I don't use await and don't wait for a call to query the user's login name.

**Comment by onein528** [comment]
fixed in #74
