### ISSUE TITLE
ItemRepeater of the Issue/PR/starred repos/repos list bug

### ISSUE THREAD

**Issue by onein528** [fluenthub-community/FluentHub#73]
**Describe the bug**

Scrolling the list view breaks the order of the muxc:ItemRepeater button list. However, the contents of the buttons in the list have only changed, and pressing the button will take me to the correct page.

**To Reproduce**

1. scroll one of those page.

**Expected behavior**

**Screenshots (optional)**

**Version**
 - Windows:win11 stable
 - FluentHub: v0.7.1

**Additional context**

**Comment by BobbyESP** [comment]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/60316747/156326835-5432bcff-6e19-45ce-bbd5-a8697a436508.png">
This is the actual problem, no?

**Comment by onein528** [comment]
yes...

**Comment by BobbyESP** [comment]
Ok!

**Comment by onein528** [comment]
maybe fixed in #74
