### ISSUE TITLE
Missing misx bundle's digital sign in v0.7.5 release package

### ISSUE THREAD

**Issue by Gaoyifei1011** [fluenthub-community/FluentHub#77]
**Describe the bug**

 Have you forget to sign this package？
![图片](https://user-images.githubusercontent.com/49179966/155921249-d9c66b8f-2cc2-4d78-a636-c17a153d95d7.png)
在打包的时候是否忘记了签名？无法正常安装。
Did you forget to sign your name when packing? The installation fails.

**To Reproduce**
1. Download release v0.7.5
2. Execute .misxbundle

**Expected behavior**

**Screenshots (optional)**

**Version**
 - Windows: win11 dev channel
 - FluentHub: v0.7.5 installing

**Additional context**

**Comment by nathayoung** [comment]
I'm getting the same thing here; failed installation.  I haven't spent much time with UWP and even less with publishing apps in general, but the previous release had a .cer file in the zip folder.  Even after manually installing that file, it failed.  Here's what I get from App Installer attepting to install both releases thus far: 
<img width="591" alt="image" src="https://user-images.githubusercontent.com/46688736/155927284-16eda5f6-7b12-4ba0-b912-2e968935368b.png">

I'm running Win 11 build 22563 (latest dev ring release) but I'm not sure if that could be causing issues. I know there was an issue publishing to the store related to Win 11 version.

**Comment by Gaoyifei1011** [comment]
所以，请您能否为这个安装包重新签一下名并再修改一下release呢？
So, can you re-sign this installation package and modify the release?

**Comment by onein528** [comment]
sorry. you need to re-sign this app bundle's certification.

**Comment by onein528** [comment]
I found that bugs what causes. I uploaded msixbuild from artifacts generated by Azure Pipelines. maybe that generated files were not signed. I'm gonna re-upload bundle.

**Comment by onein528** [comment]
sorry. it takes too time to generate store package(release build). and published v0.8.9 so now close this. if i have time, I will work on this.
