### ISSUE TITLE
Migrate checks from azure pipelines to GitHub actions

### ISSUE THREAD

**Issue by onein528** [fluenthub-community/FluentHub#78]
**Is your feature request related to a problem? Please describe.**

As the title

**Describe the solution you'd like**

Maybe it's a good idea. 

**Describe alternatives you've considered**

**Additional context**

**Screenshots (optional)**

**Comment by onein528** [comment]
https://github.com/dongle-the-gadget/WinverUWP

**Comment by BobbyESP** [comment]
We can take a look to that idea

**Comment by onein528** [comment]
- fast
- easy UI

https://github.com/dongle-the-gadget/WinverUWP/actions/runs/1864962519

**Comment by onein528** [comment]
I will not use. azure is far better.
