### ISSUE TITLE
Add Esperanto(eo) translation

### ISSUE THREAD

**Issue by victorbnl** [fluenthub-community/FluentHub#87]
I don't have Visual Studio on my computer and didn't want to install it only for that so here is the XML for the Esperanto translation.

[Resources.resw.txt](https://github.com/fluenthub-community/FluentHub/files/8238372/Resources.resw.txt)

**Comment by onein528** [comment]
thank you!
This resource will be included in the next PR and will be contributed in your name

**Comment by onein528** [comment]
and can you tell me your email in GitHub? I want do like [this](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github).

> Collect the name and email address for each co-author. If a person chooses to keep their email address private, you should use their GitHub-provided no-reply email to protect their privacy.

Go to your email settings: https://github.com/settings/emails

if your email set as private, you can get from here:

![image](https://user-images.githubusercontent.com/62196528/158056703-b149b32b-e383-4fa0-aba1-7c800d0c55ed.png)

**Comment by victorbnl** [comment]
Okay no problem, that's understandable! Also sorry for not answering your previous message I had not seen it

**Comment by onein528** [comment]
but thank you for your contributing!
