### ISSUE TITLE
Add JumpList support

### ISSUE THREAD

**Issue by luandersonn** [fluenthub-community/FluentHub#96]
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### Description

Create a JumpList of common pages and actions
Capability | Priority
:-- | :--:
Navigate to user pages (Profile, Notifications, Activities, etc.) | Must
Allow the user to pin any repository | Could
Allow account switching | Could

#### Preview
![image](https://user-images.githubusercontent.com/30560453/158753367-bffdc123-16bb-4810-9be9-c955e684cd5f.png)

**Comment by onein528** [comment]
that's nice idea!

**Comment by onein528** [comment]
do you @luandersonn have Discord account? if you have, you can join our server. Please share more off-the-record information in https://discord.gg/4nhwUKfs (available in 7 days).
